name: sync-main
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: network
        template: aws/app-template.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          RepoUrl=${{ github.server_url }}/${{ github.repository }},
          GithubConnArn=${{ secrets.GH_CONN_ARN }}
